#!/bin/bash
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}🕵️‍♂️ Running pre-commit checks on ${current_branch}${NC}"

#Let's speed things up a little bit
DOTNET_CLI_TELEMETRY_OPTOUT=1
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

echo -e "${YELLOW}🚧 Linting${NC}"

# build the project
dotnet format --check --verbosity minimal

# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}❌ Linting failed${NC}"
    echo ""
    exit $rc
fi

echo -e "${YELLOW}🛠  Build${NC}"

# build the project
dotnet build --verbosity minimal

# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}❌ Build failed${NC}"
    echo ""
    exit $rc
fi

echo -e "${YELLOW}🧪 Test${NC}"
echo ""

# run the unit tests
dotnet test --verbosity minimal

# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
    # A non-zero return code means an error occurred, so tell the user and exit
    echo -e "${RED}❌ Unit tests failed${NC}"
    echo ""
    exit $rc
fi

# Everything went OK so we can exit with a zero
echo -e "${GREEN}✅ Pre-commit checks passed!${NC}"
echo ""

exit 0